language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: linux

before_install:
  - echo -e "machine github.com\n  login gheaeckkseqrz@gmail.com\n  password $GITHUB_PASSWORD" > ~/.netrc

script:
    ############################################################################
    # Build main and tests
    ############################################################################
    - echo $TRAVIS_OS_NAME
    # MAC Dependancies
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install graphicsmagick ; fi
    # Linux Dependancies
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgtk-3-dev libglew-dev ; fi
    # COCOS SETUP
    - rm -rf *
    - sudo sed -i "backup" '133,136d' "/Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/gems/2.4.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/project.rb" || true
    - wget -nv https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
    - unzip cocos2d-x-3.17.2.zip > /dev/null
    - cd cocos2d-x-3.17.2
    - python download-deps.py
    - python setup.py -q
    - source ~/.bash_profile
    - cd ..
    - echo 'Y' | cocos new COCOS -l cpp -p ${BUNDLE_ID}
    - mv COCOS/* .
    - git checkout .
    - mkdir build && cd build
    # Build IOS
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. -DCMAKE_TOOLCHAIN_FILE=../cocos2d/cmake/ios.toolchain.cmake -GXcode -Wno-dev ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp -r ../proj.ios_mac/fastlane . ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cp fastlane/Gemfile . ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bundle install ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ssh-keyscan github.com >> ~/.ssh/known_hosts ; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bundle exec fastlane beta ; fi
    # Build Linux
    # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake .. ; fi
    # - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make -j 3 ; fi
    # Build Android
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://dl.google.com/dl/android/studio/ide-zips/3.5.0.21/android-studio-ide-191.5791312-linux.tar.gz && tar xf android-studio-ide-191.5791312-linux.tar.gz && ll -R; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ../proj.android ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then gem install bundler ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bundle install ; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then bundle exec fastlane android test ; fi
