language: objective-c

matrix:
    include:
        # - os: osx
        #   osx_image: xcode11
        # - os: osx
        #   osx_image: xcode10.2
        # - os: osx
          osx_image: xcode10.1
        - os: osx
        #   osx_image: xcode10
        # - os: osx
        #   osx_image: xcode9.4
        # - os: osx
        #   osx_image: xcode9.3
        # - os: osx
        #   osx_image: xcode9.2
        # - os: osx
        #   osx_image: xcode9.1

before_install:
     - echo -e "machine github.com\n  login gheaeckkseqrz@gmail.com\n  password $GITHUB_PASSWORD" > ~/.netrc

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - HOMEBREW_NO_AUTO_UPDATE=1 brew install graphicsmagick
     - rm -rf *
     - sudo sed -i "backup" '133,136d' "/Users/travis/.rvm/rubies/ruby-2.4.5/lib/ruby/gems/2.4.0/gems/fastlane-2.127.1/fastlane_core/lib/fastlane_core/project.rb" || true
     - wget -nv https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip > /dev/null
     - cd cocos2d-x-3.17.2
     - python download-deps.py
     - python setup.py -q
     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source /Users/travis/.bash_profile ; fi
     - cd ..
     - echo 'Y' | cocos new COCOS -l cpp -p ${BUNDLE_ID}
     - mv COCOS/* .
     - git checkout .
     - mkdir build && cd build
     - cmake .. -DCMAKE_TOOLCHAIN_FILE=../cocos2d/cmake/ios.toolchain.cmake -GXcode -Wno-dev
     - cp -r ../proj.ios_mac/fastlane .
     - cp fastlane/Gemfile .
     - bundle install
     - ssh-keyscan github.com >> ~/.ssh/known_hosts
     - bundle exec fastlane beta
