language: cpp

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - wget https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip