language: cpp

os:
  - linux
  - osx

dist: xenial

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libgtk-3-dev libglew-dev ; fi
     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask install fastlane ; fi
     - mkdir -p build
     - wget -nv https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip > /dev/null
     - cd cocos2d-x-3.17.2
     - python download-deps.py
     - python setup.py -q
     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source /home/travis/.bashrc ; fi
     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source /Users/travis/.bash_profile ; fi
     - cd ..
     - echo 'Y' | cocos new COCOS -l cpp -p ${BUNDLE_ID}
     - rm -rf proj.ios_mac/
     - mv COCOS/* .
     - git checkout .
     - ls proj.ios_mac/