language: cpp

os:
  - osx

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - sed -i '133,136d' "/Users/travis/.rvm/gems/ruby-2.4.3//gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/project.rb"
     - wget -nv https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip > /dev/null
     - cd cocos2d-x-3.17.2
     - python download-deps.py
     - python setup.py -q
     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source /Users/travis/.bash_profile ; fi
     - cd ..
     - echo 'Y' | cocos new COCOS -l cpp -p ${BUNDLE_ID}
     - rm -rf proj.ios_mac/
     - mv COCOS/* .
     - git checkout .
     - cd proj.ios_mac/
     - fastlane beta