language: cpp

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - sudo apt-get install libgtk-3-dev libglew-dev
     - mkdir -p build
     - wget https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip > /dev/null
     - cd cocos2d-x-3.17.2
     - python download-deps.py
     - python setup.py -q
     - source /home/travis/.bashrc
     - cd ..
     - echo 'Y' | cocos new -l cpp TestMe
     - cd TestMe
     - mkdir build
     - cd build
     - cmake ..
     - make