language: cpp

os:
  - osx

before_install:
  - echo -e "machine github.com\n  login gheaeckkseqrz@gmail.com\n  password $GITHUB_PASSWORD" > ~/.netrc

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - sudo gem install fastlane
     - ls -l /Users/travis/.rvm/gems/ruby-2.4.3@global/gems/fastlane-2.126.0/
     - which fastlane
     - sudo sed -i "backup" '133,136d' "/Users/travis/.rvm/gems/ruby-2.4.3@global/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/project.rb"
     - wget -nv https://digitalocean.cocos2d-x.org/Cocos2D-X/cocos2d-x-3.17.2.zip
     - unzip cocos2d-x-3.17.2.zip > /dev/null
     - cd cocos2d-x-3.17.2
     - python download-deps.py
     - python setup.py -q
     - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source /Users/travis/.bash_profile ; fi
     - cd ..
     - echo 'Y' | cocos new COCOS -l cpp -p ${BUNDLE_ID}
     - rm -rf proj.ios_mac/
     - mv COCOS/* .
     - git checkout .
     - cd proj.ios_mac/
     - ssh-keyscan github.com >> ~/.ssh/known_hosts
     - fastlane beta