# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number({build_number: latest_testflight_build_number + 1})
    update_app_identifier(app_identifier: "fr.OwlGames.CI", plist_path: "CMakeFiles/COCOS.dir/Info.plist")
    update_project_team(path: "COCOS.xcodeproj", teamid: "E5P9GHJFJ8")
    match
    gym(
      scheme: "COCOS",
      export_method: "app-store",
      sdk: "iOS 13.0",
      xcargs: {
        :PROVISIONING_PROFILE_SPECIFIER => "match AppStore fr.OwlGames.CI",
        :CODE_SIGN_IDENTITY => "iPhone Distribution",
        :CODE_SIGN_STYLE => "Manual"
      },
      export_options: {
        provisioningProfiles: {
          "fr.OwlGames.CI" => "54bc1074-aece-4408-b9fb-cf51109207bf"
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight
  end
end
